# Copyright (C) 2026  namazso <admin@namazso.eu>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Harvest libtorrent ABI facts (sizeof/alignof/enum values) at configure time
# without running code, so cross-compilation works. Each fact is compiled into
# an object file as a char array spelling "CTPROBE:<NAME>=<digits>;" where the
# digits are produced from constant expressions by the preprocessor, then
# extracted from the binary with file(STRINGS) - the same technique as CMake's
# own CheckTypeSize. The probe is compiled with the usage requirements of the
# resolved libtorrent target (via LINK_LIBRARIES), so TORRENT_ABI_VERSION and
# friends match exactly what the shim sources will see.
#
# ctorrent_abi_probe() writes
#   ${CMAKE_CURRENT_BINARY_DIR}/generated/include/ctorrent/ct_abi_config.h
# defining CT_<NAME> for every fact below.

function(_ctorrent_char_array out_var str)
  set(result "")
  string(LENGTH "${str}" len)
  math(EXPR last "${len} - 1")
  foreach(i RANGE 0 ${last})
    string(SUBSTRING "${str}" ${i} 1 ch)
    list(APPEND result "'${ch}'")
  endforeach()
  list(JOIN result "," joined)
  set(${out_var} "${joined}" PARENT_SCOPE)
endfunction()

function(ctorrent_abi_probe)
  set(includes
    "<libtorrent/version.hpp>"
    "<libtorrent/session.hpp>"
    "<libtorrent/torrent_handle.hpp>"
  )
  # NAME=constant-expression; every entry becomes a CT_<NAME> macro. Values
  # must fit in 10 decimal digits.
  set(facts
    "LT_VERSION_NUM=LIBTORRENT_VERSION_NUM"
    "LT_ABI_VERSION=TORRENT_ABI_VERSION"
    "SIZEOF_LT_TORRENT_HANDLE=sizeof(lt::torrent_handle)"
    "ALIGNOF_LT_TORRENT_HANDLE=alignof(lt::torrent_handle)"
    "SIZEOF_LT_SESSION_PROXY=sizeof(lt::session_proxy)"
    "ALIGNOF_LT_SESSION_PROXY=alignof(lt::session_proxy)"
  )

  set(src "// generated by AbiProbe.cmake - do not edit\n")
  foreach(inc IN LISTS includes)
    string(APPEND src "#include ${inc}\n")
  endforeach()
  string(APPEND src "namespace lt = libtorrent;\n")
  string(APPEND src
    "#define CT_DIG(x, d) char('0' + (((unsigned long long)(x) / d##ULL) % 10))\n"
    "#define CT_DIGITS(x) CT_DIG(x,1000000000),CT_DIG(x,100000000),\\\n"
    "  CT_DIG(x,10000000),CT_DIG(x,1000000),CT_DIG(x,100000),CT_DIG(x,10000),\\\n"
    "  CT_DIG(x,1000),CT_DIG(x,100),CT_DIG(x,10),CT_DIG(x,1)\n")
  set(idx 0)
  set(fact_names "")
  foreach(fact IN LISTS facts)
    string(FIND "${fact}" "=" eq_pos)
    string(SUBSTRING "${fact}" 0 ${eq_pos} name)
    math(EXPR val_pos "${eq_pos} + 1")
    string(SUBSTRING "${fact}" ${val_pos} -1 expr)
    list(APPEND fact_names "${name}")
    _ctorrent_char_array(name_chars "CTPROBE:${name}=")
    # External linkage keeps the arrays in the object file regardless of
    # optimization; the trailing NUL separates printable runs for
    # file(STRINGS).
    string(APPEND src "extern const char ctorrent_probe_${idx}[];\n")
    string(APPEND src
      "const char ctorrent_probe_${idx}[] = {${name_chars},CT_DIGITS(${expr}),';','\\0'};\n")
    math(EXPR idx "${idx} + 1")
  endforeach()

  set(probe_dir "${CMAKE_CURRENT_BINARY_DIR}/abi_probe")
  set(probe_src "${probe_dir}/abi_probe.cpp")
  set(probe_bin "${probe_dir}/abi_probe.bin")
  file(WRITE "${probe_src}" "${src}")

  if(NOT DEFINED CTORRENT_LT_TARGET)
    message(FATAL_ERROR "ctorrent_abi_probe: libtorrent not resolved yet")
  endif()

  # Compile to a static library: no link step, and object files never strip
  # data, so the probe strings always survive. Under -flto the "object"
  # would be LLVM bitcode / GIMPLE instead of machine code and the probe
  # strings would not appear as raw bytes, so force LTO off; this keeps
  # the probe independent of whatever CXXFLAGS the build injects.
  if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-lto")
  endif()
  set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
  # The standard must match the shim's own (see the top-level
  # CMakeLists.txt): the probe measures the layouts the shim compiles
  # against.
  try_compile(probe_ok
    SOURCES "${probe_src}"
    LINK_LIBRARIES ${CTORRENT_LT_TARGET}
    CXX_STANDARD 20
    CXX_STANDARD_REQUIRED ON
    COPY_FILE "${probe_bin}"
    OUTPUT_VARIABLE probe_log)
  if(NOT probe_ok)
    message(FATAL_ERROR "ctorrent: ABI probe failed to compile:\n${probe_log}")
  endif()

  file(STRINGS "${probe_bin}" probe_lines REGEX "CTPROBE:[A-Z0-9_]+=[0-9]+;")

  set(header "/* generated by AbiProbe.cmake - do not edit */\n")
  string(APPEND header "#ifndef CT_ABI_CONFIG_H_INCLUDED\n")
  string(APPEND header "#define CT_ABI_CONFIG_H_INCLUDED\n\n")
  foreach(line IN LISTS probe_lines)
    string(REGEX MATCH "CTPROBE:([A-Z0-9_]+)=([0-9]+);" _m "${line}")
    set(name "${CMAKE_MATCH_1}")
    # Strip leading zeros. Note: REGEX REPLACE re-anchors ^ after every
    # replacement, so the pattern must not be able to match a second time.
    string(REGEX REPLACE "^0+" "" value "${CMAKE_MATCH_2}")
    if(value STREQUAL "")
      set(value 0)
    endif()
    string(APPEND header "#define CT_${name} ${value}\n")
    list(REMOVE_ITEM fact_names "${name}")
  endforeach()
  string(APPEND header "\n#endif\n")

  if(fact_names)
    message(FATAL_ERROR
      "ctorrent: ABI probe facts missing from compiled binary: ${fact_names}")
  endif()

  set(gen_dir "${CMAKE_CURRENT_BINARY_DIR}/generated/include/ctorrent")
  file(WRITE "${probe_dir}/ct_abi_config.h" "${header}")
  file(MAKE_DIRECTORY "${gen_dir}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
    "${probe_dir}/ct_abi_config.h" "${gen_dir}/ct_abi_config.h")
endfunction()
