// Copyright (C) 2026  namazso <admin@namazso.eu>
// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//! The full settings table, in libtorrent declaration order.

use libctorrent_sys as sys;

use super::{SettingKey, SettingKind};

/// Every known setting: (key, name, kind).
pub(crate) static ALL_SETTINGS: &[(SettingKey, &str, SettingKind)] = &[
    (
        SettingKey::from_generated(sys::CT_SET_USER_AGENT),
        "user_agent",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ANNOUNCE_IP),
        "announce_ip",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_HANDSHAKE_CLIENT_VERSION),
        "handshake_client_version",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_OUTGOING_INTERFACES),
        "outgoing_interfaces",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_LISTEN_INTERFACES),
        "listen_interfaces",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PROXY_HOSTNAME),
        "proxy_hostname",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PROXY_USERNAME),
        "proxy_username",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PROXY_PASSWORD),
        "proxy_password",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_I2P_HOSTNAME),
        "i2p_hostname",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PEER_FINGERPRINT),
        "peer_fingerprint",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_BOOTSTRAP_NODES),
        "dht_bootstrap_nodes",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_NATPMP_GATEWAY),
        "natpmp_gateway",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_WEBTORRENT_STUN_SERVER),
        "webtorrent_stun_server",
        SettingKind::Str,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ALLOW_MULTIPLE_CONNECTIONS_PER_IP),
        "allow_multiple_connections_per_ip",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEND_REDUNDANT_HAVE),
        "send_redundant_have",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_USE_DHT_AS_FALLBACK),
        "use_dht_as_fallback",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UPNP_IGNORE_NONROUTERS),
        "upnp_ignore_nonrouters",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_USE_PAROLE_MODE),
        "use_parole_mode",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_AUTO_MANAGE_PREFER_SEEDS),
        "auto_manage_prefer_seeds",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DONT_COUNT_SLOW_TORRENTS),
        "dont_count_slow_torrents",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_CLOSE_REDUNDANT_CONNECTIONS),
        "close_redundant_connections",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PRIORITIZE_PARTIAL_PIECES),
        "prioritize_partial_pieces",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_RATE_LIMIT_IP_OVERHEAD),
        "rate_limit_ip_overhead",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ANNOUNCE_TO_ALL_TIERS),
        "announce_to_all_tiers",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ANNOUNCE_TO_ALL_TRACKERS),
        "announce_to_all_trackers",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PREFER_UDP_TRACKERS),
        "prefer_udp_trackers",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DISABLE_HASH_CHECKS),
        "disable_hash_checks",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ALLOW_I2P_MIXED),
        "allow_i2p_mixed",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_NO_ATIME_STORAGE),
        "no_atime_storage",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_INCOMING_STARTS_QUEUED_TORRENTS),
        "incoming_starts_queued_torrents",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_REPORT_TRUE_DOWNLOADED),
        "report_true_downloaded",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_STRICT_END_GAME_MODE),
        "strict_end_game_mode",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ENABLE_OUTGOING_UTP),
        "enable_outgoing_utp",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ENABLE_INCOMING_UTP),
        "enable_incoming_utp",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ENABLE_OUTGOING_TCP),
        "enable_outgoing_tcp",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ENABLE_INCOMING_TCP),
        "enable_incoming_tcp",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_NO_RECHECK_INCOMPLETE_RESUME),
        "no_recheck_incomplete_resume",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ANONYMOUS_MODE),
        "anonymous_mode",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_REPORT_WEB_SEED_DOWNLOADS),
        "report_web_seed_downloads",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEEDING_OUTGOING_CONNECTIONS),
        "seeding_outgoing_connections",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_NO_CONNECT_PRIVILEGED_PORTS),
        "no_connect_privileged_ports",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SMOOTH_CONNECTS),
        "smooth_connects",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ALWAYS_SEND_USER_AGENT),
        "always_send_user_agent",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_APPLY_IP_FILTER_TO_TRACKERS),
        "apply_ip_filter_to_trackers",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_BAN_WEB_SEEDS),
        "ban_web_seeds",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SUPPORT_SHARE_MODE),
        "support_share_mode",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_REPORT_REDUNDANT_BYTES),
        "report_redundant_bytes",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_LISTEN_SYSTEM_PORT_FALLBACK),
        "listen_system_port_fallback",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ANNOUNCE_CRYPTO_SUPPORT),
        "announce_crypto_support",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ENABLE_UPNP),
        "enable_upnp",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ENABLE_NATPMP),
        "enable_natpmp",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ENABLE_LSD),
        "enable_lsd",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ENABLE_DHT),
        "enable_dht",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PREFER_RC4),
        "prefer_rc4",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PROXY_HOSTNAMES),
        "proxy_hostnames",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PROXY_PEER_CONNECTIONS),
        "proxy_peer_connections",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_AUTO_SEQUENTIAL),
        "auto_sequential",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PROXY_TRACKER_CONNECTIONS),
        "proxy_tracker_connections",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ENABLE_IP_NOTIFIER),
        "enable_ip_notifier",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_PREFER_VERIFIED_NODE_IDS),
        "dht_prefer_verified_node_ids",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_RESTRICT_ROUTING_IPS),
        "dht_restrict_routing_ips",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_RESTRICT_SEARCH_IPS),
        "dht_restrict_search_ips",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_EXTENDED_ROUTING_TABLE),
        "dht_extended_routing_table",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_AGGRESSIVE_LOOKUPS),
        "dht_aggressive_lookups",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_PRIVACY_LOOKUPS),
        "dht_privacy_lookups",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_ENFORCE_NODE_ID),
        "dht_enforce_node_id",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_IGNORE_DARK_INTERNET),
        "dht_ignore_dark_internet",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_READ_ONLY),
        "dht_read_only",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PIECE_EXTENT_AFFINITY),
        "piece_extent_affinity",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_VALIDATE_HTTPS_TRACKERS),
        "validate_https_trackers",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SSRF_MITIGATION),
        "ssrf_mitigation",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ALLOW_IDNA),
        "allow_idna",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ENABLE_SET_FILE_VALID_DATA),
        "enable_set_file_valid_data",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SOCKS5_UDP_SEND_LOCAL_EP),
        "socks5_udp_send_local_ep",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PROXY_SEND_HOST_IN_CONNECT),
        "proxy_send_host_in_connect",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DISK_DISABLE_COPY_ON_WRITE),
        "disk_disable_copy_on_write",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ALLOW_MULTIPLE_CONNECTIONS_PER_PID),
        "allow_multiple_connections_per_pid",
        SettingKind::Bool,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_TRACKER_COMPLETION_TIMEOUT),
        "tracker_completion_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_TRACKER_RECEIVE_TIMEOUT),
        "tracker_receive_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_STOP_TRACKER_TIMEOUT),
        "stop_tracker_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_TRACKER_MAXIMUM_RESPONSE_LENGTH),
        "tracker_maximum_response_length",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PIECE_TIMEOUT),
        "piece_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_REQUEST_TIMEOUT),
        "request_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_REQUEST_QUEUE_TIME),
        "request_queue_time",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_ALLOWED_IN_REQUEST_QUEUE),
        "max_allowed_in_request_queue",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_OUT_REQUEST_QUEUE),
        "max_out_request_queue",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_WHOLE_PIECES_THRESHOLD),
        "whole_pieces_threshold",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PEER_TIMEOUT),
        "peer_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_URLSEED_TIMEOUT),
        "urlseed_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_URLSEED_PIPELINE_SIZE),
        "urlseed_pipeline_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_URLSEED_WAIT_RETRY),
        "urlseed_wait_retry",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_FILE_POOL_SIZE),
        "file_pool_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_FAILCOUNT),
        "max_failcount",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MIN_RECONNECT_TIME),
        "min_reconnect_time",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PEER_CONNECT_TIMEOUT),
        "peer_connect_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_CONNECTION_SPEED),
        "connection_speed",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_INACTIVITY_TIMEOUT),
        "inactivity_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UNCHOKE_INTERVAL),
        "unchoke_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_OPTIMISTIC_UNCHOKE_INTERVAL),
        "optimistic_unchoke_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_NUM_WANT),
        "num_want",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_INITIAL_PICKER_THRESHOLD),
        "initial_picker_threshold",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ALLOWED_FAST_SET_SIZE),
        "allowed_fast_set_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SUGGEST_MODE),
        "suggest_mode",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_QUEUED_DISK_BYTES),
        "max_queued_disk_bytes",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_HANDSHAKE_TIMEOUT),
        "handshake_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEND_BUFFER_LOW_WATERMARK),
        "send_buffer_low_watermark",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEND_BUFFER_WATERMARK),
        "send_buffer_watermark",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEND_BUFFER_WATERMARK_FACTOR),
        "send_buffer_watermark_factor",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_CHOKING_ALGORITHM),
        "choking_algorithm",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEED_CHOKING_ALGORITHM),
        "seed_choking_algorithm",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DISK_IO_WRITE_MODE),
        "disk_io_write_mode",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DISK_IO_READ_MODE),
        "disk_io_read_mode",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_OUTGOING_PORT),
        "outgoing_port",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_NUM_OUTGOING_PORTS),
        "num_outgoing_ports",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PEER_DSCP),
        "peer_dscp",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ACTIVE_DOWNLOADS),
        "active_downloads",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ACTIVE_SEEDS),
        "active_seeds",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ACTIVE_CHECKING),
        "active_checking",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ACTIVE_DHT_LIMIT),
        "active_dht_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ACTIVE_TRACKER_LIMIT),
        "active_tracker_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ACTIVE_LSD_LIMIT),
        "active_lsd_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ACTIVE_LIMIT),
        "active_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_AUTO_MANAGE_INTERVAL),
        "auto_manage_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEED_TIME_LIMIT),
        "seed_time_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_AUTO_SCRAPE_INTERVAL),
        "auto_scrape_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_AUTO_SCRAPE_MIN_INTERVAL),
        "auto_scrape_min_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_PEERLIST_SIZE),
        "max_peerlist_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_PAUSED_PEERLIST_SIZE),
        "max_paused_peerlist_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MIN_ANNOUNCE_INTERVAL),
        "min_announce_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_AUTO_MANAGE_STARTUP),
        "auto_manage_startup",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEEDING_PIECE_QUOTA),
        "seeding_piece_quota",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_REJECTS),
        "max_rejects",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_RECV_SOCKET_BUFFER_SIZE),
        "recv_socket_buffer_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEND_SOCKET_BUFFER_SIZE),
        "send_socket_buffer_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_PEER_RECV_BUFFER_SIZE),
        "max_peer_recv_buffer_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_OPTIMISTIC_DISK_RETRY),
        "optimistic_disk_retry",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_SUGGEST_PIECES),
        "max_suggest_pieces",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_LOCAL_SERVICE_ANNOUNCE_INTERVAL),
        "local_service_announce_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_ANNOUNCE_INTERVAL),
        "dht_announce_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UDP_TRACKER_TOKEN_EXPIRY),
        "udp_tracker_token_expiry",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_NUM_OPTIMISTIC_UNCHOKE_SLOTS),
        "num_optimistic_unchoke_slots",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_PEX_PEERS),
        "max_pex_peers",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_TICK_INTERVAL),
        "tick_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SHARE_MODE_TARGET),
        "share_mode_target",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UPLOAD_RATE_LIMIT),
        "upload_rate_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DOWNLOAD_RATE_LIMIT),
        "download_rate_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_UPLOAD_RATE_LIMIT),
        "dht_upload_rate_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UNCHOKE_SLOTS_LIMIT),
        "unchoke_slots_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_CONNECTIONS_LIMIT),
        "connections_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_CONNECTIONS_SLACK),
        "connections_slack",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UTP_TARGET_DELAY),
        "utp_target_delay",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UTP_GAIN_FACTOR),
        "utp_gain_factor",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UTP_MIN_TIMEOUT),
        "utp_min_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UTP_SYN_RESENDS),
        "utp_syn_resends",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UTP_FIN_RESENDS),
        "utp_fin_resends",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UTP_NUM_RESENDS),
        "utp_num_resends",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UTP_CONNECT_TIMEOUT),
        "utp_connect_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UTP_LOSS_MULTIPLIER),
        "utp_loss_multiplier",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MIXED_MODE_ALGORITHM),
        "mixed_mode_algorithm",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_LISTEN_QUEUE_SIZE),
        "listen_queue_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_TORRENT_CONNECT_BOOST),
        "torrent_connect_boost",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ALERT_QUEUE_SIZE),
        "alert_queue_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_METADATA_SIZE),
        "max_metadata_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_HASHING_THREADS),
        "hashing_threads",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_CHECKING_MEM_USAGE),
        "checking_mem_usage",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PREDICTIVE_PIECE_ANNOUNCE),
        "predictive_piece_announce",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_AIO_THREADS),
        "aio_threads",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_TRACKER_BACKOFF),
        "tracker_backoff",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SHARE_RATIO_LIMIT),
        "share_ratio_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEED_TIME_RATIO_LIMIT),
        "seed_time_ratio_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PEER_TURNOVER),
        "peer_turnover",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PEER_TURNOVER_CUTOFF),
        "peer_turnover_cutoff",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PEER_TURNOVER_INTERVAL),
        "peer_turnover_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_CONNECT_SEED_EVERY_N_DOWNLOAD),
        "connect_seed_every_n_download",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_HTTP_RECV_BUFFER_SIZE),
        "max_http_recv_buffer_size",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_RETRY_PORT_BIND),
        "max_retry_port_bind",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ALERT_MASK),
        "alert_mask",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_OUT_ENC_POLICY),
        "out_enc_policy",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_IN_ENC_POLICY),
        "in_enc_policy",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ALLOWED_ENC_LEVEL),
        "allowed_enc_level",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_INACTIVE_DOWN_RATE),
        "inactive_down_rate",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_INACTIVE_UP_RATE),
        "inactive_up_rate",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PROXY_TYPE),
        "proxy_type",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_PROXY_PORT),
        "proxy_port",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_I2P_PORT),
        "i2p_port",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_URLSEED_MAX_REQUEST_BYTES),
        "urlseed_max_request_bytes",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_WEB_SEED_NAME_LOOKUP_RETRY),
        "web_seed_name_lookup_retry",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_CLOSE_FILE_INTERVAL),
        "close_file_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UTP_CWND_REDUCE_TIMER),
        "utp_cwnd_reduce_timer",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_WEB_SEED_CONNECTIONS),
        "max_web_seed_connections",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_RESOLVER_CACHE_TIMEOUT),
        "resolver_cache_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_SEND_NOT_SENT_LOW_WATERMARK),
        "send_not_sent_low_watermark",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_RATE_CHOKER_INITIAL_THRESHOLD),
        "rate_choker_initial_threshold",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_UPNP_LEASE_DURATION),
        "upnp_lease_duration",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_CONCURRENT_HTTP_ANNOUNCES),
        "max_concurrent_http_announces",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_MAX_PEERS_REPLY),
        "dht_max_peers_reply",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_SEARCH_BRANCHING),
        "dht_search_branching",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_MAX_FAIL_COUNT),
        "dht_max_fail_count",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_MAX_TORRENTS),
        "dht_max_torrents",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_MAX_DHT_ITEMS),
        "dht_max_dht_items",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_MAX_PEERS),
        "dht_max_peers",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_MAX_TORRENT_SEARCH_REPLY),
        "dht_max_torrent_search_reply",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_BLOCK_TIMEOUT),
        "dht_block_timeout",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_BLOCK_RATELIMIT),
        "dht_block_ratelimit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_ITEM_LIFETIME),
        "dht_item_lifetime",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_SAMPLE_INFOHASHES_INTERVAL),
        "dht_sample_infohashes_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DHT_MAX_INFOHASHES_SAMPLE_COUNT),
        "dht_max_infohashes_sample_count",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MAX_PIECE_COUNT),
        "max_piece_count",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_METADATA_TOKEN_LIMIT),
        "metadata_token_limit",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_DISK_WRITE_MODE),
        "disk_write_mode",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MMAP_FILE_SIZE_CUTOFF),
        "mmap_file_size_cutoff",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_I2P_INBOUND_QUANTITY),
        "i2p_inbound_quantity",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_I2P_OUTBOUND_QUANTITY),
        "i2p_outbound_quantity",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_I2P_INBOUND_LENGTH),
        "i2p_inbound_length",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_I2P_OUTBOUND_LENGTH),
        "i2p_outbound_length",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_ANNOUNCE_PORT),
        "announce_port",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_I2P_INBOUND_LENGTH_VARIANCE),
        "i2p_inbound_length_variance",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_I2P_OUTBOUND_LENGTH_VARIANCE),
        "i2p_outbound_length_variance",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_NATPMP_LEASE_DURATION),
        "natpmp_lease_duration",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_MIN_WEBSOCKET_ANNOUNCE_INTERVAL),
        "min_websocket_announce_interval",
        SettingKind::Int,
    ),
    (
        SettingKey::from_generated(sys::CT_SET_WEBTORRENT_CONNECTION_TIMEOUT),
        "webtorrent_connection_timeout",
        SettingKind::Int,
    ),
];
