// Copyright (C) 2026  namazso <admin@namazso.eu>
// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import type { TorrentRow } from '@/store/torrents';

/** Complete TorrentListFields-shaped row for tests. */
export function makeTorrentRow(overrides: Partial<TorrentRow> & { uuid: string }): TorrentRow {
  const base: TorrentRow = {
    uuid: overrides.uuid,
    infoHashV1: null,
    infoHashV2: null,
    name: 'Test Torrent',
    state: 'DOWNLOADING' as TorrentRow['state'],
    progressPpm: 500_000,
    error: null,
    savePath: '/downloads',
    currentTracker: 'https://tracker.example/announce',
    nextAnnounceSeconds: 1200,
    totalDownload: 1000,
    totalUpload: 500,
    totalPayloadDownload: 900,
    totalPayloadUpload: 450,
    totalFailedBytes: 0,
    totalRedundantBytes: 0,
    totalDone: 512,
    totalSize: 2048,
    totalWantedDone: 512,
    totalWanted: 2048,
    allTimeUpload: 500,
    allTimeDownload: 1000,
    addedTime: 1_700_000_000,
    completedTime: null,
    lastSeenComplete: null,
    storageMode: 'SPARSE' as TorrentRow['storageMode'],
    queuePosition: 0,
    downloadRate: 100,
    uploadRate: 50,
    downloadPayloadRate: 90,
    uploadPayloadRate: 45,
    numSeeds: 3,
    numPeers: 5,
    numComplete: null,
    numIncomplete: null,
    listSeeds: 10,
    listPeers: 20,
    connectCandidates: 15,
    piecesHave: 4,
    distributedCopies: 1.5,
    blockSize: 16_384,
    numUploads: 2,
    numConnections: 6,
    uploadsLimit: -1,
    connectionsLimit: -1,
    uploadLimit: -1,
    downloadLimit: -1,
    upBandwidthQueue: 0,
    downBandwidthQueue: 0,
    seedRank: 0,
    needSaveResumeData: false,
    isSeeding: false,
    isFinished: false,
    isPaused: false,
    isAutoManaged: true,
    hasMetadata: true,
    sizeOnDisk: 2048,
    pieceLength: 512,
    isPrivate: false,
    isI2P: false,
    hasIncoming: false,
    movingStorage: false,
    announcingToTrackers: true,
    announcingToLsd: true,
    announcingToDht: true,
    flags: [],
  };
  return { ...base, ...overrides };
}
