#!/usr/bin/env python3
# Copyright (C) 2026  namazso <admin@namazso.eu>
# SPDX-License-Identifier: MPL-2.0
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

"""Generate the alert ID surface from libtorrent's alert_types.hpp.

Parses vendor/libtorrent (the pinned submodule) and writes:

  libctorrent/include/ctorrent/ct_alerts_generated.h  - CT_ALERT_TYPE_* ids
  libctorrent/src/alert_asserts.inc                   - static_asserts
  rbtorrent/src/alerts/generated.rs                   - AlertType enum + name table

Alert *view structs* are handwritten (they need per-field lifetime and type
judgment); this generator only guarantees the ID surface is complete and
verified. Outputs are checked in; re-run when vendor/libtorrent changes.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HPP = ROOT / "vendor/libtorrent/include/libtorrent/alert_types.hpp"


def fail(msg: str) -> None:
    sys.exit(f"gen_alerts.py: error: {msg}")


def parse() -> tuple[list[tuple[str, int, str]], int]:
    """Returns ([(alert_name, id, base_class)], num_alert_types)."""
    text = HPP.read_text()

    m = re.search(r"constexpr int num_alert_types = (\d+);", text)
    if not m:
        fail("num_alert_types not found")
    num_alert_types = int(m.group(1))

    alerts: list[tuple[str, int, str]] = []
    # preprocessor skip-depth for deprecated blocks
    depth = 0
    skip_depth: int | None = None
    current_struct: str | None = None
    current_base: str | None = None

    struct_re = re.compile(
        r"struct TORRENT_EXPORT (\w+) (?:final )?: (\w+)"
    )
    define_re = re.compile(r"TORRENT_DEFINE_ALERT(?:_PRIO)?\((\w+), (\d+)")

    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#if"):
            depth += 1
            if skip_depth is None and re.match(
                r"#if TORRENT_ABI_VERSION (==|<=|<) *\d+", stripped
            ):
                skip_depth = depth
            continue
        if stripped.startswith("#endif"):
            if skip_depth == depth:
                skip_depth = None
            depth -= 1
            continue
        if stripped.startswith("#else"):
            # no deprecated alert lives in an #else branch; treat as
            # continuation of the guard
            continue
        if skip_depth is not None:
            continue

        sm = struct_re.search(line)
        if sm:
            current_struct, current_base = sm.group(1), sm.group(2)
            continue
        dm = define_re.search(line)
        if dm:
            name, seq = dm.group(1), int(dm.group(2))
            if name != current_struct:
                fail(
                    f"macro/struct mismatch: {name} inside "
                    f"{current_struct}"
                )
            assert current_base is not None
            alerts.append((name, seq, current_base))

    if not alerts:
        fail("no alerts parsed")
    ids = [a[1] for a in alerts]
    if len(set(ids)) != len(ids):
        fail("duplicate alert ids")
    return alerts, num_alert_types


def camel(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def gen_c_header(alerts: list[tuple[str, int, str]], num_types: int) -> str:
    o = [
        "/* generated by scripts/gen_alerts.py - do not edit */",
        "#ifndef CT_ALERTS_GENERATED_H_INCLUDED",
        "#define CT_ALERTS_GENERATED_H_INCLUDED",
        "",
    ]
    for name, seq, _base in alerts:
        macro = name.removesuffix("_alert").upper()
        o.append(f"#define CT_ALERT_TYPE_{macro} {seq}")
    o += [
        "",
        f"/* lt::num_alert_types at generation time. */",
        f"#define CT_KNOWN_ALERT_COUNT {num_types}",
        "",
        "#endif",
        "",
    ]
    return "\n".join(o)


def gen_asserts(alerts: list[tuple[str, int, str]]) -> str:
    o = [
        "// generated by scripts/gen_alerts.py - do not edit",
        "// included by alerts.cpp",
    ]
    for name, _seq, _base in alerts:
        macro = name.removesuffix("_alert").upper()
        o.append(
            f"static_assert(CT_ALERT_TYPE_{macro} == lt::{name}::alert_type);"
        )
    o.append("static_assert(lt::num_alert_types >= CT_KNOWN_ALERT_COUNT);")
    o.append("")
    return "\n".join(o)


def gen_rust(alerts: list[tuple[str, int, str]], num_types: int) -> str:
    o = [
        "// generated by scripts/gen_alerts.py - do not edit",
        "",
        "use libctorrent_sys as sys;",
        "",
        "/// Identifies an alert's concrete type (`lt::alert::type()`).",
        "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]",
        "#[repr(i32)]",
        "#[non_exhaustive]",
        "pub enum AlertType {",
    ]
    for name, _seq, _base in alerts:
        macro = name.removesuffix("_alert").upper()
        variant = camel(name.removesuffix("_alert"))
        o.append(f"    {variant} = sys::CT_ALERT_TYPE_{macro} as i32,")
    o += [
        "}",
        "",
        "impl AlertType {",
        "    /// Maps a raw id; `None` for ids these bindings don't know",
        "    /// (newer libtorrent, or a removed/deprecated alert).",
        "    pub fn from_raw(raw: i32) -> Option<AlertType> {",
        "        Some(match raw {",
    ]
    for name, _seq, _base in alerts:
        macro = name.removesuffix("_alert").upper()
        variant = camel(name.removesuffix("_alert"))
        o.append(
            f"            x if x == sys::CT_ALERT_TYPE_{macro} as i32"
            f" => AlertType::{variant},"
        )
    o += [
        "            _ => return None,",
        "        })",
        "    }",
        "}",
        "",
    ]
    return "\n".join(o)


def main() -> None:
    alerts, num_types = parse()
    bases = {b for _, _, b in alerts}
    print(f"parsed {len(alerts)} alerts, num_alert_types={num_types}, bases={sorted(bases)}")

    (ROOT / "libctorrent/include/ctorrent/ct_alerts_generated.h").write_text(
        gen_c_header(alerts, num_types)
    )
    (ROOT / "libctorrent/src/alert_asserts.inc").write_text(gen_asserts(alerts))
    out = ROOT / "rbtorrent/src/alerts"
    out.mkdir(parents=True, exist_ok=True)
    (out / "generated.rs").write_text(gen_rust(alerts, num_types))
    print("wrote ct_alerts_generated.h, alert_asserts.inc, generated.rs")


if __name__ == "__main__":
    main()
